language: node_js
node_js:
- 6
before_install:
- npm install
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: _
  file: com.siemens.bt.jazz.rtc.workitemeditor.presentation.statushistory*.zip
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: jazz-community/rtc-statushistory-presentation
